"""Add fields to CommandExample model

Revision ID: a02b56232110
Revises: 8aedd844b939
Create Date: 2025-03-15 15:41:08.862908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02b56232110'
down_revision = '8aedd844b939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_examples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('command', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('output', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('setup_command', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_examples', schema=None) as batch_op:
        batch_op.drop_column('setup_command')
        batch_op.drop_column('output')
        batch_op.drop_column('command')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
