"""relationship change

Revision ID: f8ebbe6e31e8
Revises: a02b56232110
Create Date: 2025-03-15 15:53:53.155961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ebbe6e31e8'
down_revision = 'a02b56232110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_examples', schema=None) as batch_op:
        batch_op.alter_column('example',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('explanation',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_examples', schema=None) as batch_op:
        batch_op.alter_column('explanation',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('example',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
